ALTER TABLE workspace_settings
  ADD COLUMN IF NOT EXISTS llm_api_key TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS llm_base_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS embedding_api_key TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS embedding_base_url TEXT NOT NULL DEFAULT '';
