apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 3001
  selector:
    app: {{ .Release.Name }}-api
