apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-platform-secrets
type: Opaque
stringData:
  keyringJson: {{ .Values.secrets.keyringJson | quote }}
  internalServiceToken: {{ .Values.secrets.internalServiceToken | quote }}
