apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  betterAuthSecret: {{ .Values.secrets.betterAuthSecret | quote }}
  encryptionKey: {{ .Values.secrets.encryptionKey | quote }}
  openaiApiKey: {{ .Values.secrets.openaiApiKey | quote }}
